//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KursBD
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MyDBEntities : DbContext
    {
        public MyDBEntities()
            : base("name=MyDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Albums> Albums { get; set; }
        public virtual DbSet<Groups> Groups { get; set; }
        public virtual DbSet<mysek1> mysek1 { get; set; }
        public virtual DbSet<mysek2> mysek2 { get; set; }
        public virtual DbSet<mysekAll> mysekAll { get; set; }
        public virtual DbSet<Performers> Performers { get; set; }
        public virtual DbSet<Songs> Songs { get; set; }
    }
}
