//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KursBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Songs
    {
        public int id_songs { get; set; }
        public string name { get; set; }
        public string link_audio { get; set; }
        public string link_video { get; set; }
        public int id_album { get; set; }
    
        public virtual Albums Albums { get; set; }
    }
}
